### ISSUE TITLE
Switch to Captcha on Account Registration instead of Email

### ISSUE THREAD

**Issue by dnseminara** [MidAtlanticPortal/mp-accounts#1]
Currently, users register via the Portal. However, users are not activated until they receive/click on the email confirmation - to avoid spam, bots, etc. That email confirmation has an 'activate link' that the users must click on.

**Problem:** Registering users are currently not receiving email - probably in part due to the celery worker not consistently running.
- [x] Remove activation emails from being 'sent'
- [x] Add an anti-spam control (CAPTCHA?)
- [x] If CAPTCHA or anti-spam approved, register user as 'active' in Django

**Comment by pollardld** [comment]
CAPTCHA added to sandbox 
what a  🌊  🐋

**Comment by dnseminara** [comment]
@pollardld 👍
